name: Deploy to Ubuntu VPS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.0'

      - name: Install SSHPass
        run: sudo apt-get install sshpass

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Backup current project directory
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PSW }}
          script: |
            if [ -d /var/www/oazis-app ]; then
              cp -r /var/www/oazis-app /var/www/oazis-app_backup
            fi

      - name: Clean target directory on VPS
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PSW }}
          script: |
            if [ -d /var/www/oazis-app ]; then
              rm -rf /var/www/oazis-app
            fi

      - name: Copy build files via SSH
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PSW }}
          source: ".next/* static/* public/* package.json"
          target: "/var/www/oazis-app"

      - name: Install dependencies on VPS
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PSW }}
          script: |
            cd /var/www/oazis-app
            npm install --production
            sudo chown -R www-data:www-data /var/www/oazis-app

      - name: Restart Next.js application
        id: restart_service
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PSW }}
          script: |
            sudo systemctl restart oazis-app.service
        continue-on-error: true

      - name: Check if deployment succeeded
        id: check_status
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PSW }}
          script: |
            systemctl is-active oazis-app.service
        continue-on-error: true

      - name: Rollback if deployment failed
        if: steps.check_status.outcome == 'failure'
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PSW }}
          script: |
            if [ -d /var/www/oazis-app_backup ]; then
              rm -rf /var/www/oazis-app
              mv /var/www/oazis-app_backup /var/www/oazis-app
              sudo systemctl restart oazis-app.service
            fi

      - name: Cleanup backup after successful deployment
        if: steps.check_status.outcome == 'success'
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PSW }}
          script: |
            if [ -d /var/www/oazis-app_backup ]; then
              rm -rf /var/www/oazis-app_backup
            fi
